# Generated by Django 5.2.7 on 2026-07-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_class_quiz_assigned_classes_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_archived',
        ),
    ]
