# Generated by Django 5.2.7 on 2026-07-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_archived_from_class_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
    ]
