# Generated by Django 5.2.7 on 2026-07-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_questionimage_subtopicimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='option_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exam.questionoption')),
            ],
        ),
        migrations.DeleteModel(
            name='SubtopicImage',
        ),
    ]
