# Generated by Django 5.2.7 on 2026-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_optionimage_delete_subtopicimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Quiz Application', max_length=200)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
