# Generated by Django 5.2.7 on 2026-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_schoolprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='school_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='school/'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
