# Generated by Django 5.2.7 on 2026-09-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_schoolprofile_school_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bloom_classification_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('zero_shot', 'Zero-shot')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
