from django.urls import path

from . import dashboard_views as views

urlpatterns = [
    path('', views.dashboard_home, name='dashboard_home'),
    path('quizzes/', views.quiz_list, name='dashboard_quizzes'),
    path('quizzes/create/', views.quiz_create, name='dashboard_quiz_create'),
    path('quizzes/<int:quiz_id>/edit/', views.quiz_edit, name='dashboard_quiz_edit'),
    path('quizzes/<int:quiz_id>/questions/', views.quiz_questions, name='dashboard_quiz_questions'),
    path('quizzes/<int:quiz_id>/delete/', views.quiz_delete, name='dashboard_quiz_delete'),
    path('quizzes/<int:quiz_id>/duplicate/', views.quiz_duplicate, name='dashboard_quiz_duplicate'),
    path('quizzes/<int:quiz_id>/results/', views.quiz_results, name='dashboard_quiz_results'),
    path('quizzes/<int:quiz_id>/report/pdf/', views.quiz_detailed_report_pdf, name='dashboard_quiz_report_pdf'),
    path('quizzes/<int:quiz_id>/toggle/', views.quiz_toggle, name='dashboard_quiz_toggle'),
    path('quizzes/<int:quiz_id>/toggle-review/', views.quiz_toggle_review, name='dashboard_quiz_toggle_review'),
    path('results/<int:result_id>/delete/', views.result_delete, name='dashboard_result_delete'),

    path('questions/create/', views.question_create, name='dashboard_question_create'),
    path('questions/import/', views.question_import, name='dashboard_question_import'),
    path('questions/reorder/', views.question_reorder, name='dashboard_question_reorder'),
    path('questions/<int:question_id>/edit/', views.question_edit, name='dashboard_question_edit'),
    path('questions/<int:question_id>/delete/', views.question_delete, name='dashboard_question_delete'),
    path('students/', views.student_list, name='dashboard_students'),
    path('students/create/', views.student_create, name='dashboard_student_create'),
    path('students/import/', views.student_import, name='dashboard_student_import'),
    path('students/bulk-action/', views.student_bulk_action, name='dashboard_student_bulk_action'),
    path('students/<int:user_id>/edit/', views.student_edit, name='dashboard_student_edit'),
    path('students/<int:user_id>/delete/', views.student_delete, name='dashboard_student_delete'),
    path('students/<int:user_id>/reset-password/', views.student_reset_password, name='dashboard_student_reset_password'),
    path('students/<int:user_id>/toggle/', views.student_toggle, name='dashboard_student_toggle'),

    path('classes/', views.classes_list, name='dashboard_classes'),
    path('classes/create/', views.class_create, name='dashboard_class_create'),
    path('classes/get-sections-ajax/', views.get_sections_ajax, name='dashboard_classes_get_sections_ajax'),
    path('classes/student-search-ajax/', views.student_search_ajax, name='dashboard_student_search_ajax'),
    path('classes/<int:class_id>/edit/', views.class_edit, name='dashboard_class_edit'),
    path('classes/<int:class_id>/edit-ajax/', views.class_edit_ajax, name='dashboard_class_edit_ajax'),
    path('classes/<int:class_id>/delete/', views.class_delete, name='dashboard_class_delete'),
    path('classes/<int:class_id>/students/', views.class_students, name='dashboard_class_students'),
    path('classes/<int:class_id>/add-student/', views.class_add_student_ajax, name='dashboard_class_add_student'),
    path('classes/<int:class_id>/remove-student/', views.class_remove_student_ajax, name='dashboard_class_remove_student'),
    path('classes/<int:class_id>/move-student/', views.class_move_student_ajax, name='dashboard_class_move_student'),

    path('sections/create/', views.section_create, name='dashboard_section_create'),
    path('sections/<int:section_id>/edit/', views.section_edit, name='dashboard_section_edit'),
    path('sections/<int:section_id>/delete/', views.section_delete, name='dashboard_section_delete'),
    path('sections/<int:section_id>/students/', views.class_students, name='dashboard_section_students'),

    path('results/', views.results_list, name='dashboard_results'),
    path('results/export/csv/', views.results_export_csv, name='dashboard_results_export_csv'),
    path('results/export/pdf/', views.results_export_pdf, name='dashboard_results_export_pdf'),
    path('analytics/', views.analytics, name='dashboard_analytics'),
    path('analytics/<str:chart_type>/', views.analytics_detail, name='dashboard_analytics_detail'),
    path('settings/', views.settings_view, name='dashboard_settings'),
]
